---
title: "Complex in-built objects in R"
author: "Luciano Gabbanelli"
date: "2022-10-10"
output:
  html_document:
    toc: true
    toc_float: true
    collapse: true
    smooth_scroll: true
    theme: journal
    highlight: kate
    df_print: paged
    code_folding: show
---


## 1. Create a matrix from a vector

```{r}
matrix(c(1:15), nrow = 5, byrow = TRUE)
matrix(c(1:25), nrow = 5, byrow = TRUE)

matrix(c(1:10), nrow = 5, byrow = TRUE)
matrix(c(1:10), ncol = 5, byrow = TRUE)
matrix1 <- matrix(c(1:10), nrow=5 ,ncol=4, byrow = TRUE); matrix1

colnames(matrix1) <- c("1st", "2nd", "3rd", "4th")
rownames(matrix1) <- c("Row1", "Row2", "Row3", "Row4", "Row5")
matrix1

matrix1[2,3]
matrix1['Row3',]
matrix1[,'4th']


```

# 2. Ages

```{r}
set.seed(99)
ages <- round(runif(20, min = 20, max = 40)); ages
SS <- rep(c(F,T),10);SS
list_data <- list(Age=ages,Social_security=SS)

list_data
length(list_data$Social_security)
length(list_data$Age)

ages[duplicated(ages)]
unique(ages[duplicated(ages)])
# or accessing from the list:
list_data$Age[duplicated(list_data$Age)]
unique(list_data$Age[duplicated(list_data$Age)])

## I can create a table with no need to pass my vector as a factor
list_data$Age
table_freq <- table(list_data$Age);table_freq
table_freq[table_freq>1]

table(list_data$Social_security)

# Create an histogram:
list_data$Age
barplot(table_freq, ylim= c(0,4), main = "Ages of random people", xlab = "Age", ylab = "Counts", col="blue", density=30)

mean(list_data$Age)
sd(list_data$Age)

```


## 3. Sub-matrices

```{r}
M = matrix(c(1:25), nrow = 5, byrow = TRUE)
print(M)

M[,3]
sub_M <- M[M[,3] > 8,]; sub_M

diag_M <- diag(sub_M); diag_M
is.vector(diag_M)
is.list(diag_M)

vector_M <- as.vector(sub_M); vector_M
vector_M <- as.vector(t(sub_M)); vector_M

## Indices of max and min:
sub_M
max(sub_M)
which(sub_M == max(sub_M), arr.ind=TRUE)
which(sub_M == min(sub_M), arr.ind=TRUE)

M
sub_M
concat_M <- rbind(M,sub_M);concat_M
dim(concat_M)


sub_M
## Check how recursion works:
split(sub_M,c(1,1,1,2,2,2))
## Implement the partition:
list_M <- split(sub_M, rep(1:ncol(sub_M), each = nrow(sub_M)))
list_M
is.vector(list_M)
is.list(list_M)

```

## 4. Factors

```{r}
one_vector <- c(100,105,99,101,99,NA,100,99,NA,105,99,101,105,100,101,31)
one_factor <- factor(one_vector, levels = c(99,100,101,102,103,104,105))
one_factor
levels(one_factor)
levels(one_factor)[1] = "e"
one_factor
levels(one_factor)
table(one_factor)

set.seed(7)
another_vector <- sample(99:105, size=length(one_vector), replace=TRUE)
another_vector
another_factor <- factor(another_vector)
another_factor
table(another_factor)

factor(c(levels(one_factor)[one_factor], levels(another_factor)[another_factor]))
both_factors = factor(c(levels(one_factor)[one_factor], levels(another_factor)[another_factor]), levels =  levels(one_factor))
both_factors
table(both_factors)

```


## 5. Noble gasses

```{r}
atomic_number <- c(2,10,18,36,54,86,118)
strd_at_wht <- c(4.0026, 20.18, 39.95, 83.798, 131.29, NaN, NaN); strd_at_wht
group <- rep(18,7); group
gasses <- c('Helium', 'Neon', 'Argon', 'Krypton', 'Xenon', 'Radon', 'Oganesson')
features <- c('Atomic_number','Standard_atomic_weight', 'Group')

noble_gasses <- matrix(c(atomic_number,strd_at_wht,group),ncol=3,dimnames=list(gasses,features)); noble_gasses

# We need a complex data structure to store integers and characters.
df_ng=as.data.frame(noble_gasses);
df_ng

symbols_char <- 'He, Ne, Ar, Kr, Xe, Rn, Og'; symbols_char
symbols_vector <- unlist(strsplit(symbols_char, split = ', ', fixed=T)); symbols_vector
is.vector(symbols_vector)
length(symbols_vector)

df_ng$Symbol <- symbols_vector; df_ng

e_per_shell <- list()
e_per_shell[[1]] <- c(2)
e_per_shell[[2]] <- c(2,8)
e_per_shell[[3]] <- c(2,8,8)
e_per_shell[[4]] <- c(2,8,18,8)
e_per_shell[[5]] <- c(2,8,18,18,8)
e_per_shell[[6]] <- c(2,8,18,32,18,8)
e_per_shell[[7]] <- c(2,8,18,32,32,18,8)
e_per_shell

df_ng$Electrons_per_shell <- e_per_shell

df_ng
str(df_ng)
attributes(df_ng)
# Or directly
colnames(df_ng) 
rownames(df_ng) 

df_ng$Symbol[[2]]

df_ng$Electrons_per_shell

df_ng[c('Krypton','Radon'),]

subset(df_ng, (Atomic_number == 18 | Symbol == 'He'), select=c(Standard_atomic_weight))

mean(df_ng$Standard_atomic_weight, na.rm=TRUE)

```



## 6. Emplyees

```{r}
id_employees <- c(101:110);id_employees
employee_names <- c('Florentino', 'Olivia', 'Gael', 'Baldomero', 'Segundo', 'Azul', 'Mateo', 'Miranda', 'Valentina', 'Hilario')
employee_names

gross_salary <- c(37731.00, 61111.00, 55794.00, 64445.00, 43525.00, 112635.00, 57189.00, 83088.00, 122391.00, 121872.00)
gross_salary

employees.dataframe <- data.frame(id_employee=id_employees, employee_name=employee_names, gross_salary=gross_salary)

print(employees.dataframe)

employees.dataframe[5:7,]

employees.dataframe[c(3,5),c(1,3)]

employees.dataframe$years_of_experience <- c(1.5, 4.5, 4.0, 3.2, 2.0, 9.6, 3.7, 5.3, 10.3, 10.5)
print(employees.dataframe)

employees.dataframe$dependents <- c(0, 1, 0, 0, 0, 1, 0, 1, 1, 0)
employees.dataframe$dependents <- as.logical(employees.dataframe$dependents)
employees.dataframe

summary(employees.dataframe)

```